// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mock_monitoring.Models;

#nullable disable

namespace mock_monitoring.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20250612190211_SensorLog_and_Seed_Sensor")]
    partial class SensorLog_and_Seed_Sensor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mock_monitoring.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<sbyte>("Alarmen")
                        .HasColumnType("tinyint(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Sample_Period")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sensor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alarmen = (sbyte)0,
                            CreatedAt = new DateTime(2025, 6, 12, 19, 2, 10, 479, DateTimeKind.Utc).AddTicks(7530),
                            Enable = true,
                            MacAddress = "00:11:22:33:44:55",
                            Name = "Mock Sensor 1",
                            ProfileId = 1,
                            Sample_Period = 900
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
